"jobs":
  "check":
    "uses": "grafana/loki-release/.github/workflows/check.yml@main"
    "with":
      "build_image": "grafana/loki-build-image:0.34.3"
      "golang_ci_lint_version": "v1.60.3"
      "release_lib_ref": "main"
      "skip_validation": false
      "use_github_app_token": true
  "loki":
    "env":
      "BUILD_TIMEOUT": 60
      "IMAGE_PREFIX": "grafana"
      "RELEASE_LIB_REF": "main"
      "RELEASE_REPO": "grafana/loki"
    "needs":
    - "check"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "pull release library code"
      "uses": "actions/checkout@v4"
      "with":
        "path": "lib"
        "ref": "${{ env.RELEASE_LIB_REF }}"
        "repository": "grafana/loki-release"
    - "name": "pull code to release"
      "uses": "actions/checkout@v4"
      "with":
        "path": "release"
        "repository": "${{ env.RELEASE_REPO }}"
    - "name": "setup node"
      "uses": "actions/setup-node@v4"
      "with":
        "node-version": 20
    - "name": "Set up QEMU"
      "uses": "docker/setup-qemu-action@v3"
    - "name": "set up docker buildx"
      "uses": "docker/setup-buildx-action@v3"
    - "name": "Login to DockerHub (from vault)"
      "uses": "grafana/shared-workflows/actions/dockerhub-login@main"
    - "id": "weekly-version"
      "name": "Get weekly version"
      "run": |
        echo "version=$(./tools/image-tag)" >> $GITHUB_OUTPUT
      "working-directory": "release"
    - "name": "Build and push"
      "timeout-minutes": "${{ fromJSON(env.BUILD_TIMEOUT) }}"
      "uses": "docker/build-push-action@v6"
      "with":
        "build-args": "IMAGE_TAG=${{ steps.weekly-version.outputs.version }}"
        "context": "release"
        "file": "release/cmd/loki/Dockerfile"
        "platforms": "linux/amd64,linux/arm64,linux/arm"
        "push": true
        "tags": "${{ env.IMAGE_PREFIX }}/loki:${{ steps.weekly-version.outputs.version }}"
  "loki-canary":
    "env":
      "BUILD_TIMEOUT": 60
      "IMAGE_PREFIX": "grafana"
      "RELEASE_LIB_REF": "main"
      "RELEASE_REPO": "grafana/loki"
    "needs":
    - "check"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "pull release library code"
      "uses": "actions/checkout@v4"
      "with":
        "path": "lib"
        "ref": "${{ env.RELEASE_LIB_REF }}"
        "repository": "grafana/loki-release"
    - "name": "pull code to release"
      "uses": "actions/checkout@v4"
      "with":
        "path": "release"
        "repository": "${{ env.RELEASE_REPO }}"
    - "name": "setup node"
      "uses": "actions/setup-node@v4"
      "with":
        "node-version": 20
    - "name": "Set up QEMU"
      "uses": "docker/setup-qemu-action@v3"
    - "name": "set up docker buildx"
      "uses": "docker/setup-buildx-action@v3"
    - "name": "Login to DockerHub (from vault)"
      "uses": "grafana/shared-workflows/actions/dockerhub-login@main"
    - "id": "weekly-version"
      "name": "Get weekly version"
      "run": |
        echo "version=$(./tools/image-tag)" >> $GITHUB_OUTPUT
      "working-directory": "release"
    - "name": "Build and push"
      "timeout-minutes": "${{ fromJSON(env.BUILD_TIMEOUT) }}"
      "uses": "docker/build-push-action@v6"
      "with":
        "build-args": "IMAGE_TAG=${{ steps.weekly-version.outputs.version }}"
        "context": "release"
        "file": "release/cmd/loki-canary/Dockerfile"
        "platforms": "linux/amd64,linux/arm64,linux/arm"
        "push": true
        "tags": "${{ env.IMAGE_PREFIX }}/loki-canary:${{ steps.weekly-version.outputs.version }}"
  "loki-canary-boringcrypto":
    "env":
      "BUILD_TIMEOUT": 60
      "IMAGE_PREFIX": "grafana"
      "RELEASE_LIB_REF": "main"
      "RELEASE_REPO": "grafana/loki"
    "needs":
    - "check"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "pull release library code"
      "uses": "actions/checkout@v4"
      "with":
        "path": "lib"
        "ref": "${{ env.RELEASE_LIB_REF }}"
        "repository": "grafana/loki-release"
    - "name": "pull code to release"
      "uses": "actions/checkout@v4"
      "with":
        "path": "release"
        "repository": "${{ env.RELEASE_REPO }}"
    - "name": "setup node"
      "uses": "actions/setup-node@v4"
      "with":
        "node-version": 20
    - "name": "Set up QEMU"
      "uses": "docker/setup-qemu-action@v3"
    - "name": "set up docker buildx"
      "uses": "docker/setup-buildx-action@v3"
    - "name": "Login to DockerHub (from vault)"
      "uses": "grafana/shared-workflows/actions/dockerhub-login@main"
    - "id": "weekly-version"
      "name": "Get weekly version"
      "run": |
        echo "version=$(./tools/image-tag)" >> $GITHUB_OUTPUT
      "working-directory": "release"
    - "name": "Build and push"
      "timeout-minutes": "${{ fromJSON(env.BUILD_TIMEOUT) }}"
      "uses": "docker/build-push-action@v6"
      "with":
        "build-args": "IMAGE_TAG=${{ steps.weekly-version.outputs.version }}"
        "context": "release"
        "file": "release/cmd/loki-canary-boringcrypto/Dockerfile"
        "platforms": "linux/amd64,linux/arm64,linux/arm"
        "push": true
        "tags": "${{ env.IMAGE_PREFIX }}/loki-canary-boringcrypto:${{ steps.weekly-version.outputs.version }}"
  "loki-docker-driver":
    "env":
      "BUILD_TIMEOUT": 60
      "IMAGE_PREFIX": "grafana"
      "RELEASE_LIB_REF": "main"
      "RELEASE_REPO": "grafana/loki"
    "needs":
    - "check"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "pull release library code"
      "uses": "actions/checkout@v4"
      "with":
        "path": "lib"
        "ref": "${{ env.RELEASE_LIB_REF }}"
        "repository": "grafana/loki-release"
    - "name": "pull code to release"
      "uses": "actions/checkout@v4"
      "with":
        "path": "release"
        "repository": "${{ env.RELEASE_REPO }}"
    - "name": "setup node"
      "uses": "actions/setup-node@v4"
      "with":
        "node-version": 20
    - "name": "auth gcs"
      "uses": "google-github-actions/auth@v2"
      "with":
        "credentials_json": "${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}"
    - "name": "Set up QEMU"
      "uses": "docker/setup-qemu-action@v3"
    - "name": "set up docker buildx"
      "uses": "docker/setup-buildx-action@v3"
    - "id": "platform"
      "name": "parse image platform"
      "run": |
        mkdir -p images
        
        platform="$(echo "${{ matrix.platform}}" |  sed  "s/\(.*\)\/\(.*\)/\1-\2/")"
        echo "platform=${platform}" >> $GITHUB_OUTPUT
        echo "platform_short=$(echo ${{ matrix.platform }} | cut -d / -f 2)" >> $GITHUB_OUTPUT
        if [[ "${platform}" == "linux/arm64" ]]; then
          echo "plugin_arch=-arm64" >> $GITHUB_OUTPUT
        else
          echo "plugin_arch=" >> $GITHUB_OUTPUT
        fi
      "working-directory": "release"
    - "env":
        "BUILD_IMAGE": "grafana/loki-build-image:0.34.3"
        "IMAGE_TAG": "${{ needs.version.outputs.version }}"
      "if": "${{ fromJSON(needs.version.outputs.pr_created) }}"
      "name": "Build and export"
      "timeout-minutes": "${{ fromJSON(env.BUILD_TIMEOUT) }}"
      "uses": "docker/build-push-action@v6"
      "with":
        "build-args": |
          "IMAGE_TAG=${{ needs.version.outputs.version }}"
          "GOARCH=${{ steps.platform.outputs.platform_short }}"
          BUILD_IMAGE=grafana/loki-build-image:0.34.3
        "context": "release"
        "file": "release/clients/cmd/docker-driver/Dockerfile"
        "outputs": "type=docker,dest=release/images/loki-docker-driver-${{ needs.version.outputs.version}}-${{ steps.platform.outputs.platform }}.tar"
        "platforms": "${{ matrix.platform }}"
        "push": false
        "tags": "${{ env.IMAGE_PREFIX }}/loki-docker-driver:${{ needs.version.outputs.version }}-${{ steps.platform.outputs.platform_short }}"
    - "env":
        "BUILD_DIR": "release/clients/cmd/docker-driver"
        "IMAGE_TAG": "${{ needs.version.outputs.version }}"
      "if": "${{ fromJSON(needs.version.outputs.pr_created) }}"
      "name": "Package as Docker plugin"
      "run": |
        rm -rf "${{ env.BUILD_DIR }}/rootfs" || true
        mkdir "${{ env.BUILD_DIR }}/rootfs"
        tar -x -C "${{ env.BUILD_DIR }}/rootfs" -f "release/images/%s-${{ needs.version.outputs.version}}-${{ steps.platform.outputs.platform }}.tar"
        docker plugin create "${{ env.IMAGE_TAG }}${{ steps.platform.outputs.plugin_arch }}" "${{ env.BUILD_DIR }}"
      "working-directory": "release"
    - "if": "${{ fromJSON(needs.version.outputs.pr_created) }}"
      "name": "upload artifacts"
      "uses": "google-github-actions/upload-cloud-storage@v2"
      "with":
        "destination": "${{ env.BUILD_ARTIFACTS_BUCKET }}/${{ github.sha }}/images"
        "path": "release/images/loki-docker-driver-${{ needs.version.outputs.version}}-${{ steps.platform.outputs.platform }}.tar"
        "process_gcloudignore": false
    "strategy":
      "fail-fast": true
      "matrix":
        "platform":
        - "linux/amd64"
        - "linux/arm64"
  "promtail":
    "env":
      "BUILD_TIMEOUT": 60
      "IMAGE_PREFIX": "grafana"
      "RELEASE_LIB_REF": "main"
      "RELEASE_REPO": "grafana/loki"
    "needs":
    - "check"
    "runs-on": "ubuntu-latest"
    "steps":
    - "name": "pull release library code"
      "uses": "actions/checkout@v4"
      "with":
        "path": "lib"
        "ref": "${{ env.RELEASE_LIB_REF }}"
        "repository": "grafana/loki-release"
    - "name": "pull code to release"
      "uses": "actions/checkout@v4"
      "with":
        "path": "release"
        "repository": "${{ env.RELEASE_REPO }}"
    - "name": "setup node"
      "uses": "actions/setup-node@v4"
      "with":
        "node-version": 20
    - "name": "Set up QEMU"
      "uses": "docker/setup-qemu-action@v3"
    - "name": "set up docker buildx"
      "uses": "docker/setup-buildx-action@v3"
    - "name": "Login to DockerHub (from vault)"
      "uses": "grafana/shared-workflows/actions/dockerhub-login@main"
    - "id": "weekly-version"
      "name": "Get weekly version"
      "run": |
        echo "version=$(./tools/image-tag)" >> $GITHUB_OUTPUT
      "working-directory": "release"
    - "name": "Build and push"
      "timeout-minutes": "${{ fromJSON(env.BUILD_TIMEOUT) }}"
      "uses": "docker/build-push-action@v6"
      "with":
        "build-args": "IMAGE_TAG=${{ steps.weekly-version.outputs.version }}"
        "context": "release"
        "file": "release/clients/cmd/promtail/Dockerfile"
        "platforms": "linux/amd64,linux/arm64,linux/arm"
        "push": true
        "tags": "${{ env.IMAGE_PREFIX }}/promtail:${{ steps.weekly-version.outputs.version }}"
"name": "publish images"
"on":
  "pull_request": {}
  "push":
    "branches":
    - "k[0-9]+*"
    - "main"
"permissions":
  "contents": "write"
  "id-token": "write"
  "pull-requests": "write"